services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 120704
      MYSQL_DATABASE: sqldb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 120704
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p120704"]
      timeout: 20s
      retries: 10
      interval: 10s

  backend:
    build: ./backend  # Construir desde código fuente
    restart: unless-stopped
    env_file:
      - ./backend/src/config/.env
    environment:
      DATABASE_URL: mysql://appuser:120704@mysql:3307/sqldb
      JWT_SECRET: supersecret
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    command: npm run dev

  frontend:
    build: ./frontend  # Construir desde código fuente
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge