version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet

  backend1:
    build: ./backend
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/mydb
      JWT_SECRET: supersecret
    depends_on:
      - db
    networks:
      - appnet
    ports:
      - "3001:3000"

  backend2:
    build: ./backend
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/mydb
      JWT_SECRET: supersecret
    depends_on:
      - db
    networks:
      - appnet
    ports:
      - "3002:3000"

  frontend:
    build: ./frontend
    depends_on:
      - backend1
    networks:
      - appnet
    ports:
      - "4200:80"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend1
      - backend2
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
